[package]
name = "hacklet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
hacklet = { path = "../hacklet" }
binrw = "0.13.0"
clap = { version = "4.4.11", features = ["derive"] }
clap-num = "1.0.2"
log = "0.4.20"
simple_logger = "4.3.0"