[package]
name = "hacklet"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
binrw = "0.13.0"
libftd2xx = { version = "0.32.2", features = ["static"] }
simple_logger = "4.3.0"

[dev-dependencies]
rand = "0.8.4"

[lib]
name = "hacklet"
path = "src/lib.rs"
